import Plan from "../pages/PlanPage";
import Login from "../pages/LoginPage";

describe ("Plans", () => {
    const pp = new Plan();

    it ("verifyAdminLogin", () => {
            const lp = new Login();
            lp.navigateLogin();
            lp.setUsername("Sysadm.uat@gmail.com");
            lp.setPassword("Uat@@123");
            lp.clickSubmit();
            lp.verifyValidLogin();
    })

    it ("verifyPlansPage", () => {
        pp.clickOnPlans();
        pp.verifyPlansPage();
    })

    it ("verifyTiersAddNewPlanWindow", () => {
        pp.clickOnTiersAddNewPlan();
        pp.verifyTiersAddNewPlanTitle();
    })

    it ("verifyAddNewPlanWindowBlankFields", () => {
        pp.setAddNewPlanSelectPlanTypeBlank();
        pp.setAddNewPlanNameBlank();
        pp.verifyAddNewPlanNameBlankMessage();
        pp.verifyAddNewPlanSelectPlanTypeBlankMessage();
        pp.clickOnAddNewPlanCancel();
        pp.clickOnTiersAddNewPlan();
        pp.setAddNewPlanSelectProductBlank();
        pp.setAddNewPlanNameBlank();
        pp.verifyAddNewPlanSelectProductBlankMessage();
    })

    it ("verifyAddNewPlanWindowCharacterLimit", () => {
        var planname = pp.randomStringUpperCaseGenerator(31);
        var footnote = pp.randomStringUpperCaseGenerator(31);
        pp.setAddNewPlanName(planname);
        pp.setAddNewPlanFootNote(footnote);
        pp.verifyAddNewPlanNameCharacterLimit();
        pp.verifyAddNewPlanFootNoteCharacterLimit();
    })

    it ("verifyAddNewPlanWindowAllFieldsAreVisbleAsPerPlanSelection", () => {
        pp.setAddNewPlanSelectPlanType('Plan');
        pp.verifyAddNewPlanSelectCountryDropdown();
        pp.verifyAddNewPlanMonthlyPrice();
        pp.verifyAddNewPlanAnnualPrice();
        pp.verifyAddNewPlanSelectFeatureType();
        pp.verifyAddNewPlanSelectFeature();
        pp.verifyAddNewPlanValue();
        pp.setAddNewPlanSelectPlanType('Add-On');
        pp.verifyAddNewPlanTierOccurrence();
        pp.verifyAddNewPlanSelectCountryDropdown();
        pp.verifyAddNewPlanPrice();
        pp.verifyAddNewPlanSelectFeature();
        pp.verifyAddNewPlanValue();
        pp.verifyAddNewPlanAddPlanButtonIsDisabled();
    })

    it ("verifyAddNewPlanWithBasicPlanFalseAddedSuccessfully", () => {
        pp.clickOnAddNewPlanCancel();
        pp.clickOnTiersAddNewPlan();
        var planNameLandline = pp.randomStringUpperCaseGenerator(5);
        var footNoteLandline = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueLandline = pp.randomNumberGenerator(2);
        var singleDigitValueLandline = pp.randomNumberGenerator(1);
        pp.setAddNewPlanName(planNameLandline + ' ' + planNameLandline);
        pp.setAddNewPlanFootNote(footNoteLandline);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Basic');
        pp.setAddNewPlanSelectProduct('Landline Texting');
        pp.setAddNewPlanSelectPlanType('Plan');
        pp.setAddNewPlanIsPrivate('False');
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueLandline + '.' + twoDigitValueLandline);
        pp.setAddNewPlanAnnualPrice(twoDigitValueLandline + '.' + twoDigitValueLandline);
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Credits per month');
        pp.setAddNewPlanValue(twoDigitValueLandline);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Group Texting');
        pp.setAddNewPlanValue(twoDigitValueLandline);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('End User Creation');
        pp.setAddNewPlanValue(singleDigitValueLandline);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Keywords');
        pp.setAddNewPlanValue(singleDigitValueLandline);
        pp.clickOnAddNewPlanNewFeature();
        // pp.setAddNewPlanSelectFeatureType('Main Feature');
        // pp.setAddNewPlanSelectFeature('10DLC Registration');
        // pp.clickOnAddNewPlanUnlimited();
        // pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Contacts');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MMS');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Emojis');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Dashboard');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Notifications');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Scheduled Messages');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MS Teams Extension');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Auto Replies');
        pp.clickOnAddNewPlanSubmit();
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameLandline + ' ' + planNameLandline);
        pp.verifyAddNewPlanRowGridCount();
        var planNameVoip = pp.randomStringUpperCaseGenerator(5);
        var footNoteVoip = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueVoip = pp.randomNumberGenerator(2);
        var singleDigitValueVoip = pp.randomNumberGenerator(1);
        pp.setAddNewPlanName(planNameVoip + ' ' + planNameVoip);
        pp.setAddNewPlanFootNote(footNoteVoip);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Basic');
        pp.setAddNewPlanSelectProduct('VoIP Texting');
        pp.setAddNewPlanSelectPlanType('Plan');
        pp.setAddNewPlanIsPrivate('False');
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueVoip + '.' + twoDigitValueVoip);
        pp.setAddNewPlanAnnualPrice(twoDigitValueVoip + '.' + twoDigitValueVoip);
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Credits per month');
        pp.setAddNewPlanValue(twoDigitValueVoip);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Group Texting');
        pp.setAddNewPlanValue(twoDigitValueVoip);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('End User Creation');
        pp.setAddNewPlanValue(singleDigitValueVoip);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Keywords');
        pp.setAddNewPlanValue(singleDigitValueVoip);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Contacts');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MMS');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Emojis');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Dashboard');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Notifications');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Scheduled Messages');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MS Teams Extension');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Auto Replies');
        pp.clickOnAddNewPlanSubmit();
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameVoip + ' ' + planNameVoip);
        pp.verifyAddNewPlanRowGridCount();
        var planNameTeams = pp.randomStringUpperCaseGenerator(5);
        var footNoteTeams = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueTeams = pp.randomNumberGenerator(2);
        var singleDigitValueTeams = pp.randomNumberGenerator(1);
        pp.setAddNewPlanName(planNameTeams + ' ' + planNameTeams);
        pp.setAddNewPlanFootNote(footNoteTeams);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Basic');
        pp.setAddNewPlanSelectProduct('MS Teams Calling and Texting');
        pp.setAddNewPlanSelectPlanType('Plan');
        pp.setAddNewPlanIsPrivate('False');
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueTeams + '.' + twoDigitValueTeams);
        pp.setAddNewPlanAnnualPrice(twoDigitValueTeams + '.' + twoDigitValueTeams);
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Credits per month');
        pp.setAddNewPlanValue(twoDigitValueTeams);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Group Texting');
        pp.setAddNewPlanValue(twoDigitValueTeams);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('End User Creation');
        pp.setAddNewPlanValue(singleDigitValueTeams);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Keywords');
        pp.setAddNewPlanValue(singleDigitValueTeams);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Contacts');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MMS');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Emojis');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Dashboard');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Notifications');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Scheduled Messages');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MS Teams Extension');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Auto Replies');
        pp.clickOnAddNewPlanSubmit();
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameTeams + ' ' + planNameTeams);
        pp.verifyAddNewPlanRowGridCount();
        var planNameToll = pp.randomStringUpperCaseGenerator(5);
        var footNoteToll = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueToll = pp.randomNumberGenerator(2);
        var singleDigitValueToll = pp.randomNumberGenerator(1);
        pp.setAddNewPlanName(planNameToll + ' ' + planNameToll);
        pp.setAddNewPlanFootNote(footNoteToll);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Basic');
        pp.setAddNewPlanSelectProduct('Toll-Free Texting');
        pp.setAddNewPlanSelectPlanType('Plan');
        pp.setAddNewPlanIsPrivate('False');
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueToll + '.' + twoDigitValueToll);
        pp.setAddNewPlanAnnualPrice(twoDigitValueToll + '.' + twoDigitValueToll);
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Credits per month');
        pp.setAddNewPlanValue(twoDigitValueToll);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Group Texting');
        pp.setAddNewPlanValue(twoDigitValueToll);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('End User Creation');
        pp.setAddNewPlanValue(singleDigitValueToll);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Keywords');
        pp.setAddNewPlanValue(singleDigitValueToll);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Contacts');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MMS');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Emojis');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Dashboard');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Notifications');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Scheduled Messages');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MS Teams Extension');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Auto Replies');
        pp.clickOnAddNewPlanSubmit();
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameToll + ' ' + planNameToll);
        pp.verifyAddNewPlanRowGridCount();
    })

    it ("verifyAddNewPlanWithBasicPlanTrueAddedSuccessfully", () => {
        pp.clickOnTiersAddNewPlan();
        var planNameLandline = pp.randomStringUpperCaseGenerator(5);
        var footNoteLandline = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueLandline = pp.randomNumberGenerator(2);
        var singleDigitValueLandline = pp.randomNumberGenerator(1);
        pp.setAddNewPlanName(planNameLandline + ' ' + planNameLandline);
        pp.setAddNewPlanFootNote(footNoteLandline);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Basic');
        pp.setAddNewPlanSelectProduct('Landline Texting');
        pp.setAddNewPlanSelectPlanType('Plan');
        pp.setAddNewPlanIsPrivate('True');
        pp.setAddNewPlanSelectOrganization();
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueLandline + '.' + twoDigitValueLandline);
        pp.setAddNewPlanAnnualPrice(twoDigitValueLandline + '.' + twoDigitValueLandline);
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Credits per month');
        pp.setAddNewPlanValue(twoDigitValueLandline);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Group Texting');
        pp.setAddNewPlanValue(twoDigitValueLandline);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('End User Creation');
        pp.setAddNewPlanValue(singleDigitValueLandline);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Keywords');
        pp.setAddNewPlanValue(singleDigitValueLandline);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Contacts');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MMS');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Emojis');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Dashboard');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Notifications');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Scheduled Messages');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MS Teams Extension');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Auto Replies');
        pp.clickOnAddNewPlanSubmit();
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameLandline + ' ' + planNameLandline);
        pp.verifyAddNewPlanRowGridCount();
        pp.clickOnTiersAddNewPlan();
        var planNameVoip = pp.randomStringUpperCaseGenerator(5);
        var footNoteVoip = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueVoip = pp.randomNumberGenerator(2);
        var singleDigitValueVoip = pp.randomNumberGenerator(1);
        pp.setAddNewPlanName(planNameVoip + ' ' + planNameVoip);
        pp.setAddNewPlanFootNote(footNoteVoip);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Basic');
        pp.setAddNewPlanSelectProduct('VoIP Texting');
        pp.setAddNewPlanSelectPlanType('Plan');
        pp.setAddNewPlanIsPrivate('True');
        pp.setAddNewPlanSelectOrganization();
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueVoip + '.' + twoDigitValueVoip);
        pp.setAddNewPlanAnnualPrice(twoDigitValueVoip + '.' + twoDigitValueVoip);
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Credits per month');
        pp.setAddNewPlanValue(twoDigitValueVoip);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Group Texting');
        pp.setAddNewPlanValue(twoDigitValueVoip);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('End User Creation');
        pp.setAddNewPlanValue(singleDigitValueVoip);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Keywords');
        pp.setAddNewPlanValue(singleDigitValueVoip);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Contacts');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MMS');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Emojis');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Dashboard');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Notifications');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Scheduled Messages');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MS Teams Extension');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Auto Replies');
        pp.clickOnAddNewPlanSubmit();
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameVoip + ' ' + planNameVoip);
        pp.verifyAddNewPlanRowGridCount();
        pp.clickOnTiersAddNewPlan();
        var planNameTeams = pp.randomStringUpperCaseGenerator(5);
        var footNoteTeams = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueTeams = pp.randomNumberGenerator(2);
        var singleDigitValueTeams = pp.randomNumberGenerator(1);
        pp.setAddNewPlanName(planNameTeams + ' ' + planNameTeams);
        pp.setAddNewPlanFootNote(footNoteTeams);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Basic');
        pp.setAddNewPlanSelectProduct('MS Teams Calling and Texting');
        pp.setAddNewPlanSelectPlanType('Plan');
        pp.setAddNewPlanIsPrivate('True');
        pp.setAddNewPlanSelectOrganization();
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueTeams + '.' + twoDigitValueTeams);
        pp.setAddNewPlanAnnualPrice(twoDigitValueTeams + '.' + twoDigitValueTeams);
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Credits per month');
        pp.setAddNewPlanValue(twoDigitValueTeams);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Group Texting');
        pp.setAddNewPlanValue(twoDigitValueTeams);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('End User Creation');
        pp.setAddNewPlanValue(singleDigitValueTeams);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Keywords');
        pp.setAddNewPlanValue(singleDigitValueTeams);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Contacts');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MMS');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Emojis');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Dashboard');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Notifications');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Scheduled Messages');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MS Teams Extension');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Auto Replies');
        pp.clickOnAddNewPlanSubmit();
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameTeams + ' ' + planNameTeams);
        pp.verifyAddNewPlanRowGridCount();
        pp.clickOnTiersAddNewPlan();
        var planNameToll = pp.randomStringUpperCaseGenerator(5);
        var footNoteToll = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueToll = pp.randomNumberGenerator(2);
        var singleDigitValueToll = pp.randomNumberGenerator(1);
        pp.setAddNewPlanName(planNameToll + ' ' + planNameToll);
        pp.setAddNewPlanFootNote(footNoteToll);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Basic');
        pp.setAddNewPlanSelectProduct('Toll-Free Texting');
        pp.setAddNewPlanSelectPlanType('Plan');
        pp.setAddNewPlanIsPrivate('True');
        pp.setAddNewPlanSelectOrganization();
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueToll + '.' + twoDigitValueToll);
        pp.setAddNewPlanAnnualPrice(twoDigitValueToll + '.' + twoDigitValueToll);
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Credits per month');
        pp.setAddNewPlanValue(twoDigitValueToll);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Group Texting');
        pp.setAddNewPlanValue(twoDigitValueToll);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('End User Creation');
        pp.setAddNewPlanValue(singleDigitValueToll);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Keywords');
        pp.setAddNewPlanValue(singleDigitValueToll);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Contacts');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MMS');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Emojis');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Dashboard');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Notifications');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Scheduled Messages');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MS Teams Extension');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Auto Replies');
        pp.clickOnAddNewPlanSubmit();
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameToll + ' ' + planNameToll);
        pp.verifyAddNewPlanRowGridCount();
    })

    it ("verifyAddNewPlanWithStandardPlanFalseAddedSuccessfully", () => {
        pp.clickOnTiersAddNewPlan();
        var planNameLandline = pp.randomStringUpperCaseGenerator(5);
        var footNoteLandline = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueLandline = pp.randomNumberGenerator(2);
        var singleDigitValueLandline = pp.randomNumberGenerator(1);
        pp.setAddNewPlanName(planNameLandline + ' ' + planNameLandline);
        pp.setAddNewPlanFootNote(footNoteLandline);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Standard');
        pp.setAddNewPlanSelectProduct('Landline Texting');
        pp.setAddNewPlanSelectPlanType('Plan');
        pp.setAddNewPlanIsPrivate('False');
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueLandline + '.' + twoDigitValueLandline);
        pp.setAddNewPlanAnnualPrice(twoDigitValueLandline + '.' + twoDigitValueLandline);
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Group Texting');
        pp.setAddNewPlanValue(twoDigitValueLandline);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('End User Creation');
        pp.setAddNewPlanValue(singleDigitValueLandline);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Keywords');
        pp.setAddNewPlanValue(singleDigitValueLandline);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Contacts');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MMS');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Emojis');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Dashboard');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Notifications');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Scheduled Messages');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MS Teams Extension');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Auto Replies');
        pp.clickOnAddNewPlanSubmit();
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameLandline + ' ' + planNameLandline);
        pp.verifyAddNewPlanRowGridCount();
        pp.clickOnTiersAddNewPlan();
        var planNameVoip = pp.randomStringUpperCaseGenerator(5);
        var footNoteVoip = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueVoip = pp.randomNumberGenerator(2);
        var singleDigitValueVoip = pp.randomNumberGenerator(1);
        pp.setAddNewPlanName(planNameVoip + ' ' + planNameVoip);
        pp.setAddNewPlanFootNote(footNoteVoip);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Standard');
        pp.setAddNewPlanSelectProduct('VoIP Texting');
        pp.setAddNewPlanSelectPlanType('Plan');
        pp.setAddNewPlanIsPrivate('False');
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueVoip + '.' + twoDigitValueVoip);
        pp.setAddNewPlanAnnualPrice(twoDigitValueVoip + '.' + twoDigitValueVoip);
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Group Texting');
        pp.setAddNewPlanValue(twoDigitValueVoip);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('End User Creation');
        pp.setAddNewPlanValue(singleDigitValueVoip);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Keywords');
        pp.setAddNewPlanValue(singleDigitValueVoip);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Contacts');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MMS');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Emojis');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Dashboard');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Notifications');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Scheduled Messages');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MS Teams Extension');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Auto Replies');
        pp.clickOnAddNewPlanSubmit();
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameVoip + ' ' + planNameVoip);
        pp.verifyAddNewPlanRowGridCount();
        pp.clickOnTiersAddNewPlan();
        var planNameTeams = pp.randomStringUpperCaseGenerator(5);
        var footNoteTeams = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueTeams = pp.randomNumberGenerator(2);
        var singleDigitValueTeams = pp.randomNumberGenerator(1);
        pp.setAddNewPlanName(planNameTeams + ' ' + planNameTeams);
        pp.setAddNewPlanFootNote(footNoteTeams);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Standard');
        pp.setAddNewPlanSelectProduct('MS Teams Calling and Texting');
        pp.setAddNewPlanSelectPlanType('Plan');
        pp.setAddNewPlanIsPrivate('False');
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueTeams + '.' + twoDigitValueTeams);
        pp.setAddNewPlanAnnualPrice(twoDigitValueTeams + '.' + twoDigitValueTeams);
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Group Texting');
        pp.setAddNewPlanValue(twoDigitValueTeams);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('End User Creation');
        pp.setAddNewPlanValue(singleDigitValueTeams);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Keywords');
        pp.setAddNewPlanValue(singleDigitValueTeams);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Contacts');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MMS');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Emojis');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Dashboard');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Notifications');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Scheduled Messages');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MS Teams Extension');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Auto Replies');
        pp.clickOnAddNewPlanSubmit();
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameTeams + ' ' + planNameTeams);
        pp.verifyAddNewPlanRowGridCount();
        pp.clickOnTiersAddNewPlan();
        var planNameToll = pp.randomStringUpperCaseGenerator(5);
        var footNoteToll = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueToll = pp.randomNumberGenerator(2);
        var singleDigitValueToll = pp.randomNumberGenerator(1);
        pp.setAddNewPlanName(planNameToll + ' ' + planNameToll);
        pp.setAddNewPlanFootNote(footNoteToll);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Standard');
        pp.setAddNewPlanSelectProduct('Toll-Free Texting');
        pp.setAddNewPlanSelectPlanType('Plan');
        pp.setAddNewPlanIsPrivate('False');
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueToll + '.' + twoDigitValueToll);
        pp.setAddNewPlanAnnualPrice(twoDigitValueToll + '.' + twoDigitValueToll);
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Group Texting');
        pp.setAddNewPlanValue(twoDigitValueToll);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('End User Creation');
        pp.setAddNewPlanValue(singleDigitValueToll);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Keywords');
        pp.setAddNewPlanValue(singleDigitValueToll);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Contacts');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MMS');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Emojis');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Dashboard');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Notifications');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Scheduled Messages');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MS Teams Extension');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Auto Replies');
        pp.clickOnAddNewPlanSubmit();
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameToll + ' ' + planNameToll);
        pp.verifyAddNewPlanRowGridCount();
    })

    it ("verifyAddNewPlanWithStandardPlanTrueAddedSuccessfully", () => {
        pp.clickOnTiersAddNewPlan();
        var planNameLandline = pp.randomStringUpperCaseGenerator(5);
        var footNoteLandline = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueLandline = pp.randomNumberGenerator(2);
        var singleDigitValueLandline = pp.randomNumberGenerator(1);
        pp.setAddNewPlanName(planNameLandline + ' ' + planNameLandline);
        pp.setAddNewPlanFootNote(footNoteLandline);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Standard');
        pp.setAddNewPlanSelectProduct('Landline Texting');
        pp.setAddNewPlanSelectPlanType('Plan');
        pp.setAddNewPlanIsPrivate('True');
        pp.setAddNewPlanSelectOrganization();
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueLandline + '.' + twoDigitValueLandline);
        pp.setAddNewPlanAnnualPrice(twoDigitValueLandline + '.' + twoDigitValueLandline);
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Group Texting');
        pp.setAddNewPlanValue(twoDigitValueLandline);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('End User Creation');
        pp.setAddNewPlanValue(singleDigitValueLandline);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Keywords');
        pp.setAddNewPlanValue(singleDigitValueLandline);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Contacts');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MMS');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Emojis');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Dashboard');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Notifications');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Scheduled Messages');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MS Teams Extension');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Auto Replies');
        pp.clickOnAddNewPlanSubmit();
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameLandline + ' ' + planNameLandline);
        pp.verifyAddNewPlanRowGridCount();
        pp.clickOnTiersAddNewPlan();
        var planNameVoip = pp.randomStringUpperCaseGenerator(5);
        var footNoteVoip = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueVoip = pp.randomNumberGenerator(2);
        var singleDigitValueVoip = pp.randomNumberGenerator(1);
        pp.setAddNewPlanName(planNameVoip + ' ' + planNameVoip);
        pp.setAddNewPlanFootNote(footNoteVoip);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Standard');
        pp.setAddNewPlanSelectProduct('VoIP Texting');
        pp.setAddNewPlanSelectPlanType('Plan');
        pp.setAddNewPlanIsPrivate('True');
        pp.setAddNewPlanSelectOrganization();
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueVoip + '.' + twoDigitValueVoip);
        pp.setAddNewPlanAnnualPrice(twoDigitValueVoip + '.' + twoDigitValueVoip);
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Group Texting');
        pp.setAddNewPlanValue(twoDigitValueVoip);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('End User Creation');
        pp.setAddNewPlanValue(singleDigitValueVoip);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Keywords');
        pp.setAddNewPlanValue(singleDigitValueVoip);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Contacts');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MMS');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Emojis');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Dashboard');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Notifications');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Scheduled Messages');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MS Teams Extension');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Auto Replies');
        pp.clickOnAddNewPlanSubmit();
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameVoip + ' ' + planNameVoip);
        pp.verifyAddNewPlanRowGridCount();
        pp.clickOnTiersAddNewPlan();
        var planNameTeams = pp.randomStringUpperCaseGenerator(5);
        var footNoteTeams = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueTeams = pp.randomNumberGenerator(2);
        var singleDigitValueTeams = pp.randomNumberGenerator(1);
        pp.setAddNewPlanName(planNameTeams + ' ' + planNameTeams);
        pp.setAddNewPlanFootNote(footNoteTeams);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Standard');
        pp.setAddNewPlanSelectProduct('MS Teams Calling and Texting');
        pp.setAddNewPlanSelectPlanType('Plan');
        pp.setAddNewPlanIsPrivate('True');
        pp.setAddNewPlanSelectOrganization();
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueTeams + '.' + twoDigitValueTeams);
        pp.setAddNewPlanAnnualPrice(twoDigitValueTeams + '.' + twoDigitValueTeams);
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Group Texting');
        pp.setAddNewPlanValue(twoDigitValueTeams);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('End User Creation');
        pp.setAddNewPlanValue(singleDigitValueTeams);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Keywords');
        pp.setAddNewPlanValue(singleDigitValueTeams);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Contacts');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MMS');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Emojis');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Dashboard');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Notifications');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Scheduled Messages');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MS Teams Extension');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Auto Replies');
        pp.clickOnAddNewPlanSubmit();
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameTeams + ' ' + planNameTeams);
        pp.verifyAddNewPlanRowGridCount();
        pp.clickOnTiersAddNewPlan();
        var planNameToll = pp.randomStringUpperCaseGenerator(5);
        var footNoteToll = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueToll = pp.randomNumberGenerator(2);
        var singleDigitValueToll = pp.randomNumberGenerator(1);
        pp.setAddNewPlanName(planNameToll + ' ' + planNameToll);
        pp.setAddNewPlanFootNote(footNoteToll);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Standard');
        pp.setAddNewPlanSelectProduct('Toll-Free Texting');
        pp.setAddNewPlanSelectPlanType('Plan');
        pp.setAddNewPlanIsPrivate('True');
        pp.setAddNewPlanSelectOrganization();
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueToll + '.' + twoDigitValueToll);
        pp.setAddNewPlanAnnualPrice(twoDigitValueToll + '.' + twoDigitValueToll);
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Group Texting');
        pp.setAddNewPlanValue(twoDigitValueToll);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('End User Creation');
        pp.setAddNewPlanValue(singleDigitValueToll);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Keywords');
        pp.setAddNewPlanValue(singleDigitValueToll);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Contacts');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MMS');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Emojis');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Dashboard');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Notifications');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Scheduled Messages');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MS Teams Extension');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Auto Replies');
        pp.clickOnAddNewPlanSubmit();
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameToll + ' ' + planNameToll);
        pp.verifyAddNewPlanRowGridCount();
    })
    
    it ("verifyAddNewPlanWithStandardAddonFalseOneTimeAddedSuccessfully", () => {
        pp.clickOnTiersAddNewPlan();
        var planNameLandline = pp.randomStringUpperCaseGenerator(5);
        var footNoteLandline = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueLandline = pp.randomNumberGenerator(2);
        pp.setAddNewPlanName(planNameLandline);
        pp.setAddNewPlanFootNote(footNoteLandline);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Standard');
        pp.setAddNewPlanSelectProduct('Landline Texting');
        pp.setAddNewPlanSelectPlanType('Add-On');
        pp.setAddNewPlanIsPrivate('False');
        pp.setAddNewPlanSelectTierOccurrence('One Time');
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueLandline + '.' + twoDigitValueLandline);
        pp.setAddNewPlanSelectFeature('Credits per month');
        pp.clickOnAddNewPlanUnlimited();
        pp.clickEditWindowSaveButton(); 
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameLandline);
        pp.verifyAddNewPlanAddonRowGridCount();
        pp.clickOnTiersAddNewPlan();
        var planNameVoip = pp.randomStringUpperCaseGenerator(5);
        var footNoteVoip = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueVoip = pp.randomNumberGenerator(2);
        pp.setAddNewPlanName(planNameVoip);
        pp.setAddNewPlanFootNote(footNoteVoip);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Standard');
        pp.setAddNewPlanSelectProduct('VoIP Texting');
        pp.setAddNewPlanSelectPlanType('Add-On');
        pp.setAddNewPlanIsPrivate('False');
        pp.setAddNewPlanSelectTierOccurrence('One Time');
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueVoip + '.' + twoDigitValueVoip);
        pp.setAddNewPlanSelectFeature('Group Texting');
        pp.setAddNewPlanValue(twoDigitValueVoip);
        pp.clickEditWindowSaveButton(); 
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameVoip);
        pp.verifyAddNewPlanAddonRowGridCount();
        pp.clickOnTiersAddNewPlan();
        var planNameTeams = pp.randomStringUpperCaseGenerator(5);
        var footNoteTeams = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueTeams = pp.randomNumberGenerator(2);
        var singleDigitValueTeams = pp.randomNumberGenerator(1);
        pp.setAddNewPlanName(planNameTeams);
        pp.setAddNewPlanFootNote(footNoteTeams);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Standard');
        pp.setAddNewPlanSelectProduct('MS Teams Calling and Texting');
        pp.setAddNewPlanSelectPlanType('Add-On');
        pp.setAddNewPlanIsPrivate('False');
        pp.setAddNewPlanSelectTierOccurrence('One Time');
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueTeams + '.' + twoDigitValueTeams);
        pp.setAddNewPlanSelectFeature('End User Creation');
        pp.setAddNewPlanValue(singleDigitValueTeams);
        pp.clickEditWindowSaveButton(); 
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameTeams);
        pp.verifyAddNewPlanAddonRowGridCount();
        pp.clickOnTiersAddNewPlan();
        var planNameToll = pp.randomStringUpperCaseGenerator(5);
        var footNoteToll = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueToll = pp.randomNumberGenerator(2);
        var singleDigitValueToll = pp.randomNumberGenerator(1);
        pp.setAddNewPlanName(planNameToll);
        pp.setAddNewPlanFootNote(footNoteToll);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Standard');
        pp.setAddNewPlanSelectProduct('Toll-Free Texting');
        pp.setAddNewPlanSelectPlanType('Add-On');
        pp.setAddNewPlanIsPrivate('False');
        pp.setAddNewPlanSelectTierOccurrence('One Time');
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueToll + '.' + twoDigitValueToll);
        pp.setAddNewPlanSelectFeature('Keywords');
        pp.setAddNewPlanValue(singleDigitValueToll);
        pp.clickEditWindowSaveButton(); 
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameToll);
        pp.verifyAddNewPlanAddonRowGridCount();
        pp.clickOnTiersAddNewPlan();
        var planNameLandline01 = pp.randomStringUpperCaseGenerator(5);
        var footNoteLandline01 = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueLandline01 = pp.randomNumberGenerator(2);
        pp.setAddNewPlanName(planNameLandline01);
        pp.setAddNewPlanFootNote(footNoteLandline01);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Standard');
        pp.setAddNewPlanSelectProduct('Landline Texting');
        pp.setAddNewPlanSelectPlanType('Add-On');
        pp.setAddNewPlanIsPrivate('False');
        pp.setAddNewPlanSelectTierOccurrence('One Time');
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueLandline01 + '.' + twoDigitValueLandline01);
        pp.setAddNewPlanSelectFeature('Keywords');
        pp.clickOnAddNewPlanUnlimited();
        pp.clickEditWindowSaveButton(); 
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameLandline01);
        pp.verifyAddNewPlanAddonRowGridCount();
    })

    it ("verifyAddNewPlanWithStandardAddonFalseRecurringAddedSuccessfully", () => {
        pp.clickOnTiersAddNewPlan();
        var planNameLandline = pp.randomStringUpperCaseGenerator(5);
        var footNoteLandline = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueLandline = pp.randomNumberGenerator(2);
        pp.setAddNewPlanName(planNameLandline);
        pp.setAddNewPlanFootNote(footNoteLandline);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Standard');
        pp.setAddNewPlanSelectProduct('Landline Texting');
        pp.setAddNewPlanSelectPlanType('Add-On');
        pp.setAddNewPlanIsPrivate('False');
        pp.setAddNewPlanSelectTierOccurrence('Recurring');
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueLandline + '.' + twoDigitValueLandline);
        pp.setAddNewPlanSelectFeature('Credits per month');
        pp.clickOnAddNewPlanUnlimited();
        pp.clickEditWindowSaveButton(); 
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameLandline);
        pp.verifyAddNewPlanAddonRowGridCount();
        pp.clickOnTiersAddNewPlan();
        var planNameVoip = pp.randomStringUpperCaseGenerator(5);
        var footNoteVoip = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueVoip = pp.randomNumberGenerator(2);
        pp.setAddNewPlanName(planNameVoip);
        pp.setAddNewPlanFootNote(footNoteVoip);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Standard');
        pp.setAddNewPlanSelectProduct('VoIP Texting');
        pp.setAddNewPlanSelectPlanType('Add-On');
        pp.setAddNewPlanIsPrivate('False');
        pp.setAddNewPlanSelectTierOccurrence('Recurring');
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueVoip + '.' + twoDigitValueVoip);
        pp.setAddNewPlanSelectFeature('Group Texting');
        pp.setAddNewPlanValue(twoDigitValueVoip);
        pp.clickEditWindowSaveButton(); 
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameVoip);
        pp.verifyAddNewPlanAddonRowGridCount();
        pp.clickOnTiersAddNewPlan();
        var planNameTeams = pp.randomStringUpperCaseGenerator(5);
        var footNoteTeams = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueTeams = pp.randomNumberGenerator(2);
        var singleDigitValueTeams = pp.randomNumberGenerator(1);
        pp.setAddNewPlanName(planNameTeams);
        pp.setAddNewPlanFootNote(footNoteTeams);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Standard');
        pp.setAddNewPlanSelectProduct('MS Teams Calling and Texting');
        pp.setAddNewPlanSelectPlanType('Add-On');
        pp.setAddNewPlanIsPrivate('False');
        pp.setAddNewPlanSelectTierOccurrence('Recurring');
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueTeams + '.' + twoDigitValueTeams);
        pp.setAddNewPlanSelectFeature('End User Creation');
        pp.setAddNewPlanValue(singleDigitValueTeams);
        pp.clickEditWindowSaveButton(); 
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameTeams);
        pp.verifyAddNewPlanAddonRowGridCount();
        pp.clickOnTiersAddNewPlan();
        var planNameToll = pp.randomStringUpperCaseGenerator(5);
        var footNoteToll = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueToll = pp.randomNumberGenerator(2);
        var singleDigitValueToll = pp.randomNumberGenerator(1);
        pp.setAddNewPlanName(planNameToll);
        pp.setAddNewPlanFootNote(footNoteToll);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Standard');
        pp.setAddNewPlanSelectProduct('Toll-Free Texting');
        pp.setAddNewPlanSelectPlanType('Add-On');
        pp.setAddNewPlanIsPrivate('False');
        pp.setAddNewPlanSelectTierOccurrence('Recurring');
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueToll + '.' + twoDigitValueToll);
        pp.setAddNewPlanSelectFeature('Keywords');
        pp.setAddNewPlanValue(singleDigitValueToll);
        pp.clickEditWindowSaveButton(); 
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameToll);
        pp.verifyAddNewPlanAddonRowGridCount();
        pp.clickOnTiersAddNewPlan();
        var planNameLandline01 = pp.randomStringUpperCaseGenerator(5);
        var footNoteLandline01 = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueLandline01 = pp.randomNumberGenerator(2);
        pp.setAddNewPlanName(planNameLandline01);
        pp.setAddNewPlanFootNote(footNoteLandline01);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Standard');
        pp.setAddNewPlanSelectProduct('Landline Texting');
        pp.setAddNewPlanSelectPlanType('Add-On');
        pp.setAddNewPlanIsPrivate('False');
        pp.setAddNewPlanSelectTierOccurrence('Recurring');
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueLandline01 + '.' + twoDigitValueLandline01);
        pp.setAddNewPlanSelectFeature('Keywords');
        pp.clickOnAddNewPlanUnlimited();
        pp.clickEditWindowSaveButton(); 
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameLandline01);
        pp.verifyAddNewPlanAddonRowGridCount();
    })

    it ("verifyAddNewPlanWithStandardAddonTrueOneTimeAddedSuccessfully", () => {
        pp.clickOnTiersAddNewPlan();
        var planNameLandline = pp.randomStringUpperCaseGenerator(5);
        var footNoteLandline = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueLandline = pp.randomNumberGenerator(2);
        pp.setAddNewPlanName(planNameLandline);
        pp.setAddNewPlanFootNote(footNoteLandline);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Standard');
        pp.setAddNewPlanSelectProduct('Landline Texting');
        pp.setAddNewPlanSelectPlanType('Add-On');
        pp.setAddNewPlanIsPrivate('True');
        pp.setAddNewPlanSelectOrganization();
        pp.setAddNewPlanSelectTierOccurrence('One Time');
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueLandline + '.' + twoDigitValueLandline);
        pp.setAddNewPlanSelectFeature('Credits per month');
        pp.clickOnAddNewPlanUnlimited();
        pp.clickEditWindowSaveButton(); 
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameLandline);
        pp.verifyAddNewPlanAddonRowGridCount();
        pp.clickOnTiersAddNewPlan();
        var planNameVoip = pp.randomStringUpperCaseGenerator(5);
        var footNoteVoip = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueVoip = pp.randomNumberGenerator(2);
        pp.setAddNewPlanName(planNameVoip);
        pp.setAddNewPlanFootNote(footNoteVoip);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Standard');
        pp.setAddNewPlanSelectProduct('VoIP Texting');
        pp.setAddNewPlanSelectPlanType('Add-On');
        pp.setAddNewPlanIsPrivate('True');
        pp.setAddNewPlanSelectOrganization();
        pp.setAddNewPlanSelectTierOccurrence('One Time');
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueVoip + '.' + twoDigitValueVoip);
        pp.setAddNewPlanSelectFeature('Group Texting');
        pp.setAddNewPlanValue(twoDigitValueVoip);
        pp.clickEditWindowSaveButton(); 
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameVoip);
        pp.verifyAddNewPlanAddonRowGridCount();
        pp.clickOnTiersAddNewPlan();
        var planNameTeams = pp.randomStringUpperCaseGenerator(5);
        var footNoteTeams = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueTeams = pp.randomNumberGenerator(2);
        var singleDigitValueTeams = pp.randomNumberGenerator(1);
        pp.setAddNewPlanName(planNameTeams);
        pp.setAddNewPlanFootNote(footNoteTeams);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Standard');
        pp.setAddNewPlanSelectProduct('MS Teams Calling and Texting');
        pp.setAddNewPlanSelectPlanType('Add-On');
        pp.setAddNewPlanIsPrivate('True');
        pp.setAddNewPlanSelectOrganization();
        pp.setAddNewPlanSelectTierOccurrence('One Time');
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueTeams + '.' + twoDigitValueTeams);
        pp.setAddNewPlanSelectFeature('End User Creation');
        pp.setAddNewPlanValue(singleDigitValueTeams);
        pp.clickEditWindowSaveButton(); 
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameTeams);
        pp.verifyAddNewPlanAddonRowGridCount();
        pp.clickOnTiersAddNewPlan();
        var planNameToll = pp.randomStringUpperCaseGenerator(5);
        var footNoteToll = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueToll = pp.randomNumberGenerator(2);
        var singleDigitValueToll = pp.randomNumberGenerator(1);
        pp.setAddNewPlanName(planNameToll);
        pp.setAddNewPlanFootNote(footNoteToll);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Standard');
        pp.setAddNewPlanSelectProduct('Toll-Free Texting');
        pp.setAddNewPlanSelectPlanType('Add-On');
        pp.setAddNewPlanIsPrivate('True');
        pp.setAddNewPlanSelectOrganization();
        pp.setAddNewPlanSelectTierOccurrence('One Time');
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueToll + '.' + twoDigitValueToll);
        pp.setAddNewPlanSelectFeature('Keywords');
        pp.setAddNewPlanValue(singleDigitValueToll);
        pp.clickEditWindowSaveButton(); 
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameToll);
        pp.verifyAddNewPlanAddonRowGridCount();
        pp.clickOnTiersAddNewPlan();
        var planNameLandline01 = pp.randomStringUpperCaseGenerator(5);
        var footNoteLandline01 = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueLandline01 = pp.randomNumberGenerator(2);
        pp.setAddNewPlanName(planNameLandline01);
        pp.setAddNewPlanFootNote(footNoteLandline01);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Standard');
        pp.setAddNewPlanSelectProduct('Landline Texting');
        pp.setAddNewPlanSelectPlanType('Add-On');
        pp.setAddNewPlanIsPrivate('True');
        pp.setAddNewPlanSelectOrganization();
        pp.setAddNewPlanSelectTierOccurrence('One Time');
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueLandline01 + '.' + twoDigitValueLandline01);
        pp.setAddNewPlanSelectFeature('Keywords');
        pp.clickOnAddNewPlanUnlimited();
        pp.clickEditWindowSaveButton(); 
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameLandline01);
        pp.verifyAddNewPlanAddonRowGridCount();
    })

    it ("verifyAddNewPlanWithStandardAddonTrueRecurringAddedSuccessfully", () => {
        pp.clickOnTiersAddNewPlan();
        var planNameLandline = pp.randomStringUpperCaseGenerator(5);
        var footNoteLandline = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueLandline = pp.randomNumberGenerator(2);
        pp.setAddNewPlanName(planNameLandline);
        pp.setAddNewPlanFootNote(footNoteLandline);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Standard');
        pp.setAddNewPlanSelectProduct('Landline Texting');
        pp.setAddNewPlanSelectPlanType('Add-On');
        pp.setAddNewPlanIsPrivate('True');
        pp.setAddNewPlanSelectOrganization();
        pp.setAddNewPlanSelectTierOccurrence('Recurring');
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueLandline + '.' + twoDigitValueLandline);
        pp.setAddNewPlanSelectFeature('Credits per month');
        pp.clickOnAddNewPlanUnlimited();
        pp.clickEditWindowSaveButton(); 
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameLandline);
        pp.verifyAddNewPlanAddonRowGridCount();
        pp.clickOnTiersAddNewPlan();
        var planNameVoip = pp.randomStringUpperCaseGenerator(5);
        var footNoteVoip = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueVoip = pp.randomNumberGenerator(2);
        pp.setAddNewPlanName(planNameVoip);
        pp.setAddNewPlanFootNote(footNoteVoip);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Standard');
        pp.setAddNewPlanSelectProduct('VoIP Texting');
        pp.setAddNewPlanSelectPlanType('Add-On');
        pp.setAddNewPlanIsPrivate('True');
        pp.setAddNewPlanSelectOrganization();
        pp.setAddNewPlanSelectTierOccurrence('Recurring');
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueVoip + '.' + twoDigitValueVoip);
        pp.setAddNewPlanSelectFeature('Group Texting');
        pp.setAddNewPlanValue(twoDigitValueVoip);
        pp.clickEditWindowSaveButton(); 
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameVoip);
        pp.verifyAddNewPlanAddonRowGridCount();
        pp.clickOnTiersAddNewPlan();
        var planNameTeams = pp.randomStringUpperCaseGenerator(5);
        var footNoteTeams = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueTeams = pp.randomNumberGenerator(2);
        var singleDigitValueTeams = pp.randomNumberGenerator(1);
        pp.setAddNewPlanName(planNameTeams);
        pp.setAddNewPlanFootNote(footNoteTeams);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Standard');
        pp.setAddNewPlanSelectProduct('MS Teams Calling and Texting');
        pp.setAddNewPlanSelectPlanType('Add-On');
        pp.setAddNewPlanIsPrivate('True');
        pp.setAddNewPlanSelectOrganization();
        pp.setAddNewPlanSelectTierOccurrence('Recurring');
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueTeams + '.' + twoDigitValueTeams);
        pp.setAddNewPlanSelectFeature('End User Creation');
        pp.setAddNewPlanValue(singleDigitValueTeams);
        pp.clickEditWindowSaveButton(); 
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameTeams);
        pp.verifyAddNewPlanAddonRowGridCount();
        pp.clickOnTiersAddNewPlan();
        var planNameToll = pp.randomStringUpperCaseGenerator(5);
        var footNoteToll = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueToll = pp.randomNumberGenerator(2);
        var singleDigitValueToll = pp.randomNumberGenerator(1);
        pp.setAddNewPlanName(planNameToll);
        pp.setAddNewPlanFootNote(footNoteToll);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Standard');
        pp.setAddNewPlanSelectProduct('Toll-Free Texting');
        pp.setAddNewPlanSelectPlanType('Add-On');
        pp.setAddNewPlanIsPrivate('True');
        pp.setAddNewPlanSelectOrganization();
        pp.setAddNewPlanSelectTierOccurrence('Recurring');
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueToll + '.' + twoDigitValueToll);
        pp.setAddNewPlanSelectFeature('Keywords');
        pp.setAddNewPlanValue(singleDigitValueToll);
        pp.clickEditWindowSaveButton(); 
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameToll);
        pp.verifyAddNewPlanAddonRowGridCount();
        pp.clickOnTiersAddNewPlan();
        var planNameLandline01 = pp.randomStringUpperCaseGenerator(5);
        var footNoteLandline01 = pp.randomStringUpperCaseGenerator(5);
        var twoDigitValueLandline01 = pp.randomNumberGenerator(2);
        pp.setAddNewPlanName(planNameLandline01);
        pp.setAddNewPlanFootNote(footNoteLandline01);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Standard');
        pp.setAddNewPlanSelectProduct('Landline Texting');
        pp.setAddNewPlanSelectPlanType('Add-On');
        pp.setAddNewPlanIsPrivate('True');
        pp.setAddNewPlanSelectOrganization();
        pp.setAddNewPlanSelectTierOccurrence('Recurring');
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twoDigitValueLandline01 + '.' + twoDigitValueLandline01);
        pp.setAddNewPlanSelectFeature('Keywords');
        pp.clickOnAddNewPlanUnlimited();
        pp.clickEditWindowSaveButton(); 
        pp.verifyAddNewPlanAddedSuccessfully();
        pp.setAddNewPlanSearchBox(planNameLandline01);
        pp.verifyAddNewPlanAddonRowGridCount();
    })

    it ("verifyAddNewPlanUnhideSuccessfully", () => {
        pp.clickOnKebabMenu();
        pp.clickOnKebabMenuUnhide();
        pp.verifyAddNewPlanWindowUnhideText();
        pp.clickOnUnhideWindowCancelButton();
        pp.clickOnKebabMenu();
        pp.clickOnKebabMenuUnhide();
        pp.clickOnUnhideWindowUnhideButton();
        pp.verifyAddNewPlanUnhideSuccessfullyText();
    })

    it ("verifyAddNewPlanHideSuccessfully", () => {
        pp.clickOnKebabMenu();
        pp.clickOnKebabMenuHide();
        pp.verifyAddNewPlanWindowHideText();
        pp.clickOnhideWindowCancelButton();
        pp.clickOnKebabMenu();
        pp.clickOnKebabMenuHide();
        pp.clickOnHideWindowHideButton();
        pp.verifyAddNewPlanHideSuccessfullyText();
    })

    it ("verifyAddNewPlanEditWindow", () => {
        pp.clickOnKebabMenu();
        pp.clickOnKebabMenuEdit();
        var footNote = pp.randomStringUpperCaseGenerator(5);
        var twodigitvalue = pp.randomNumberGenerator(2);
        pp.setAddNewPlanFootNote(footNote);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Basic');
        pp.setAddNewPlanSelectProduct('Landline Texting');
        pp.setAddNewPlanSelectPlanType('Add-On');
        pp.setAddNewPlanSelectTierOccurrence('One Time');
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twodigitvalue + '.' + twodigitvalue);
        pp.setAddNewPlanSelectFeature('Credits per month');
        pp.setAddNewPlanValue(twodigitvalue);
        pp.clickEditWindowSaveButton(); 
        pp.verifyAddNewPlanEditedSuccessfully();
    })

    it ("verifyAddNewPlanDuplicateWindow", () => {
        pp.clickOnKebabMenu();
        pp.clickOnKebabMenuDuplicate();
        var planName = pp.randomStringUpperCaseGenerator(5);
        var footNote = pp.randomStringUpperCaseGenerator(5);
        var twodigitvalue = pp.randomNumberGenerator(2);
        var singledigitvalue = pp.randomNumberGenerator(1);
        pp.setAddNewPlanName(planName + ' ' + planName);
        pp.setAddNewPlanFootNote(footNote);
        pp.setAddNewPlanSelectGracePeriod('No Grace Period');
        pp.setAddNewPlanSelectDashboard('Standard');
        pp.setAddNewPlanSelectProduct('Landline Texting');
        pp.setAddNewPlanSelectPlanType('Plan');
        pp.setAddNewPlanSelectCountry('United States');
        pp.setAddNewPlanMonthlyPrice(twodigitvalue + '.' + twodigitvalue);
        pp.setAddNewPlanAnnualPrice(twodigitvalue + '.' + twodigitvalue);
        pp.setAddNewPlanSelectFeature('Credits per month');
        pp.setAddNewPlanValue(twodigitvalue);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Group Texting');
        pp.setAddNewPlanValue(twodigitvalue);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('End User Creation');
        pp.setAddNewPlanValue(singledigitvalue);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Main Feature');
        pp.setAddNewPlanSelectFeature('Keywords');
        pp.setAddNewPlanValue(singledigitvalue);
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Contacts');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MMS');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Emojis');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Dashboard');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Notifications');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Scheduled Messages');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('MS Teams Extension');
        pp.clickOnAddNewPlanNewFeature();
        pp.setAddNewPlanSelectFeatureType('Additional Feature');
        pp.setAddNewPlanSelectFeature('Auto Replies');
        pp.clickDuplicateWindowDuplicatePlanButton();
        pp.verifyAddNewPlanDuplicatedSuccessfully();
        pp.setAddNewPlanSearchBox(planName + ' ' + planName);
        pp.verifyAddNewPlanRowGridCount();
    })

}
)